name: timecop
description: Simple private time tracking.
version: 1.7.2+43
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite_common_ffi:
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  path: ^1.8.2
  collection: ^1.16.0
  sqflite: ^2.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^10.1.0
  random_color: ^1.0.6-nullsafety
  flutter_slidable: ^2.0.0
  about: ^2.0.1
  url_launcher: ^6.0.20
  flutter_svg: ^1.1.4
  flutter_material_color_picker: ^1.1.0+2
  flutter_datetime_picker: ^1.5.1
  csv: ^5.0.1
  path_provider: ^2.0.9
  share_plus: ^5.0.0
  cross_file: ^0.3.3
  shared_preferences: ^2.0.13
  fl_chart: ^0.55.1
  card_swiper: ^2.0.4
  flutter_typeahead: ^4.0.0
  flutter_app_badger: ^1.3.0
  numberpicker: ^2.1.1
  file_picker: ^5.0.1
  flutter_local_notifications: ^12.0.2
  flutter_markdown: ^0.6.9
  package_info_plus: ^2.0.0
  xdg_directories: ^0.2.0+1
  fluent: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_driver:
    sdk: flutter
  test: ^1.17.10
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  #until screenshots updates on the package repo..
  #screenshots: ^2.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  adaptive_icon_background: "#263238"
  adaptive_icon_foreground: "icon_android_fg.png"

flutter:
  uses-material-design: true
  assets:
    - README.md
    - CHANGELOG.md
    - CONTRIBUTORS.md
    - icon.no-bg.svg
    - icon.no-bg.cyan.svg
    - fonts/LICENSE-PublicSans.md
    - l10n/
  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: fonts/PublicSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PublicSans-Bold.ttf
          weight: 700
